#!/bin/bash

FORGE_SITE="http://files.minecraftforge.net/maven/net/minecraftforge/forge"

die () {
  echo $*
  exit 1
}

[ ! -d ${MC_HOME} ] && die "Data directory does not exist"

# If data directory has data, set variable so we don't download the forge installer
if [ -z "$(ls -A ${MC_HOME})" ]; then
  echo "Data dir empty"
  DATA_DIR_EMPTY=1
else
  echo "Data dir not empty"
  DATA_DIR_EMPTY=0
fi

if [ ! -d ${MC_HOME}/server ]; then
  echo "Creating ${MC_HOME}/server directory"
  mkdir ${MC_HOME}/server || die "Failed to create directory ${MC_HOME}/server"
fi

FORGE_INSTALLER_JAR="forge-${MINECRAFT_VERSION}-${FORGE_VERSION}-${MINECRAFT_VERSION}-installer.jar"
[ -z ${FORGE_URL} ] && FORGE_URL="${FORGE_SITE}/${MINECRAFT_VERSION}-${FORGE_VERSION}-${MINECRAFT_VERSION}/${FORGE_INSTALLER_JAR}"
FORGE_JAR="forge-${MINECRAFT_VERSION}-${FORGE_VERSION}-${MINECRAFT_VERSION}-universal.jar"

if [ ! -z "$FML_CONFIRM" ]; then
  FML_CONFIRM="-Dfml.queryResult=${FML_CONFIRM}"
else
  FML_CONFIRM=""
fi

[ ! -f "${MC_HOME}/server/start.sh" ] && cp /opt/default_start.sh ${MC_HOME}/server/start.sh
chmod +x ${MC_HOME}/server/start.sh

[ "${DATA_DIR_EMPTY}" == "0" ] && exit 0

echo "Downloading Forge Installer ${FORGE_URL}"
curl -o /tmp/${FORGE_INSTALLER_JAR} ${FORGE_URL}
[ "$?" != "0" ] && die "curl command failed"
cd ${MC_HOME}/server && java -jar /tmp/${FORGE_INSTALLER_JAR} --installServer
[ "$?" != "0" ] && die "Forge java installer failed"
rm -f /tmp/${FORGE_INSTALLER_JAR}

[ ! -f ${MC_HOME}/server/eula.txt ] && touch ${MC_HOME}/server/eula.txt
[ "$(grep 'eula=true' ${MC_HOME}/server/eula.txt)" == "" ] && cat <<'EOF' > ${MC_HOME}/server/eula.txt
eula=true
EOF
